20190529 1350
mozilla-l10n/lockwiseios-l10n pull request #5
Opened 2019-05-29 19:54 UTC by devinreams

Latest based on https://github.com/mozilla-lockwise/lockwise-ios/pull/992

Looks like it really wants to translate those bundle names (CredentialProvider, Firefox Lockwise).

But this should expose the Face ID usage description as noted at https://github.com/mozilla-lockwise/lockwise-ios/issues/1009

2019-05-29 21:45 UTC, Pike reviewed
Would the paths continue to roundtrip with the `Strings/en.lproj` in them?

2019-05-29 21:45 UTC, Pike commented on de/lockwise-ios.xliff
> +  <file original="lockbox-ios/Common/Resources/Strings/en.lproj/InfoPlist.strings" source-language="en" target-language="de" datatype="plaintext">
The `Strings/en.lproj` path insert is surprising to me.

2019-05-29 22:12 UTC, devinreams commented
>Would the paths continue to roundtrip with the Strings/en.lproj in them?

@Pike Yes I believe so. I think the original inclusion of the `InfoPlist.strings` was at an incorrect path in the project so after doing some cleanup and removing of redundant files (and I just tried it again) this is what the result is.

I looked at the `Localizable.strings` and its included in Xcode and configure the same way. So I'm not sure why this would change now but don't see any way to "put it back" on this side.

![image](https://user-images.githubusercontent.com/49511/58595018-8d29a780-822c-11e9-84a0-df83e3ff154d.png)


![image](https://user-images.githubusercontent.com/49511/58595010-84d16c80-822c-11e9-99e9-506fc74e1063.png)

2019-05-29 22:41 UTC, Pike commented
Looping in Matjaz. @mathjazz, can you take a look at this, and see if the changed file path drops many localizations in Pontoon? Might just be a single Lockwise string at this point?

2019-05-30 05:26 UTC, flodolo commented
> Looping in Matjaz. @mathjazz, can you take a look at this, and see if the changed file path drops many localizations in Pontoon? Might just be a single Lockwise string at this point?

The update script already dropped them: it reads the strings, and inject them in the template. If the file path changed, that translation doesn't exist in the translated XLIFF. 

If you look at German, you'll see that the translation for `Lockwise` has been removed.

P.S. Reminder that Matjaz is on PTO for the next week ;-)

2019-05-31 10:33 UTC, Pike requested changes
OK, dug a little deeper, and this is actually a regression in @joeyg's export branch.

https://github.com/joeyg/ios-l10n-scripts/blob/fb87542e86e6ead31e44012fd929db833dfc99c3/export-locales.sh#L98 doesn't catch the new `/Strings/` path.

I'd be OK with just the few string being lost and keeping the `/Strings/` in the filepath, but I think we need a fix to at least remove the `en.lproj` in the path.

2019-05-31 14:14 UTC, joeyg commented
@pike ahh great catch. Sorry about that

2019-06-10 21:50 UTC, devinreams commented
>I think we need a fix to at least remove the en.lproj in the path.

OK, since this blocks additional strings being exported (we may have 1 for a future release, fairly uncommon) I will submit a change to @joeyg's fork/branch and re-submit an extract here.

2019-06-22 18:23 UTC, devinreams commented
Revised output at #6

2019-06-22 18:23 UTC, closed without merging